import { Text } from 'react-native';
import { ArupakaHeaderView } from 'react-native-header-arupaka-r';
const App = () => {
  return (
    <ArupakaHeaderView
      showBackButton
      headerTitle={'header'}
      footInsetColor="blue"
    >
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
      <Text>aaaa</Text>
    </ArupakaHeaderView>
  );
};

export default App;
